services:
  qr-inventory-api-1:
    build:
      target: production
      # dockerfile: Dockerfile
    environment:
      NODE_ENV: developmentdocker
    command: npm run start:prod
    depends_on:
      - postgres_test

  #${VARIABLE:?err} чтобы ошибка была

  postgres_test:
    image: postgres
    restart: always
    container_name: ${POSTGRES_TEST_HOST:?err}
    command: postgres -c port=${POSTGRES_TEST_PORT:?err} -c listen_addresses='*'
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB:?err}
      POSTGRES_USER: ${POSTGRES_TEST_USER:?err}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:?err}
    networks:
      - api

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:?err}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:?err}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - ${PGADMIN_PORT:?err}:80
    networks:
      - api
    depends_on:
      - postgres_test

  nginx:
    build:
      args:
        NODE_ENV: development
    command: >
      /bin/sh -c "envsubst < /etc/nginx/nginx.conf.development.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

