services:
  api:
    container_name: nest_api
    build:
      dockerfile: Dockerfile
      context: .
      target: build
    env_file:
      - .env
    environment:
      NODE_ENV: production
    command: npm run start:prod
    ports:
      - "${GLOBAL_PORT}:${APP_PORT}"
  postgres:
    image: postgres
    restart: always
    container_name: ${POSTGRES_HOST}
    command: postgres -c port=${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  postgres_test:
    image: postgres
    restart: always
    container_name: ${POSTGRES_TEST_HOST}
    command: postgres -c port=${POSTGRES_TEST_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
    ports:
      - "${POSTGRES_TEST_PORT}:${POSTGRES_TEST_PORT}"
volumes:
  docker-nest-invetorying:
