services:
  qr-inventory-api:
    build:
      target: build
    environment:
      NODE_ENV: developmentdocker
    command: npm run start:dev
    depends_on:
      - postgres_test

  #${VARIABLE:?err} чтобы ошибка была

  postgres_test:
    image: postgres
    restart: always
    container_name: ${POSTGRES_TEST_HOST}
    command: postgres -c port=${POSTGRES_TEST_PORT} -c listen_addresses='*'
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
    networks:
      - api

  pgadmin:
    depends_on:
      - postgres_test

  nginx:
    build:
      args:
        NODE_ENV: development
    command: >
      /bin/sh -c "envsubst < /etc/nginx/nginx.conf.production.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

