services:
  qr-inventory-api-1:
    container_name: qr-inventory-api-1
    build:
      dockerfile: Dockerfile
      context: .
      target: build
    env_file:
      - .env
    environment:
      APP_PORT: 5001
      NODE_ENV: developmentdocker
    command: npm run start:prod
    networks:
      - qr-inventory-proxy
      - api

  nginx:
    container_name: reverse-proxy
    image: nginx
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    env_file:
      - .env
    depends_on:
      - qr-inventory-api-1
    networks:
      - qr-inventory-proxy
      - api

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:?}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:?}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - api

networks:
  api:
    name: api
    driver: bridge
  qr-inventory-proxy:
    name: qr-inventory
